// Code generated by goctl. DO NOT EDIT.
package types

type FileReq struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Method string `json:"method"`
}

type FileResp struct {
	Context string `json:"context"`
	Message string `json:"message"`
}

type FileListReq struct {
	Type string `json:"type"`
}

type FileListResp struct {
	Name string `json:"name"`
	Date string `json:"date"`
}

type LogResp struct {
	Context string `json:"context"`
}

type CommandReq struct {
	Selection            string `form:"selection"`
	Domain               string `form:"domain,optional"`
	IP                   string `form:"ip,optional"`
	CASubject            string `form:"caSubject,optional"`
	CAValidityDays       int    `form:"caValidityDays,optional"`
	RootSubject          string `form:"rootSubject,optional"`
	RootValidityDays     int    `form:"rootValidityDays,optional"`
	SerialNumber         int    `form:"serialNumber,optional"`
	RootOnlySubject      string `form:"rootOnlySubject,optional"`
	RootOnlyValidityDays int    `form:"rootOnlyValidityDays,optional"`
	RootOnlySerialNumber int    `form:"rootOnlySerialNumber,optional"`
}

type CommandResp struct {
	Message string `json:"message"`
}
