// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"self-signed-certificate-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file",
				Handler: FileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/filelist",
				Handler: FileListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/command",
				Handler: CommandHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/log",
				Handler: LogHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
